[build]
command = "npm run build"  # Replace with your build command
publish = "dist"  # Replace with the path to your build output directory

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200
